name: Daily Salesforce Org Backup

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Install Salesforce CLI
      run: npm install --global @salesforce/cli

    - name: Authenticate to Salesforce
      run: |
        echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
        sf org login sfdx-url --sfdx-url-file auth.txt --alias backuporg

    - name: Pull metadata from Salesforce
      run: |
        sf project retrieve start \
          --target-org backuporg \
          --metadata ApexClass \
          --metadata ApexTrigger \
          --metadata CustomObject \
          --metadata Flow \
          --metadata Layout

    - name: Commit backup to GitHub   
      run: |
         git config user.email "github-actions@github.com"
         git config user.name "github-actions[bot]"

    
         git rm --cached auth.txt || true

    
         git add .

         if git diff --staged --quiet; then
            echo "Nothing to commit"
         else
            git commit -m "Auto backup $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin main
        fi

    - name: Notify Slack on Success
      if: success()
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload: |
          {"text":"✅ Salesforce backup completed successfully!"}

    - name: Notify Slack on Failure
      if: failure()
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload: |
          {"text":"❌ Salesforce backup FAILED! Check GitHub Actions."}
